CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
CREATE TABLE country (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    name character varying(100) NOT NULL,
    iso2 character varying(2),
    created_at timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    CONSTRAINT "PK_country" PRIMARY KEY (id)
);

CREATE TABLE department (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    country_id integer NOT NULL,
    name character varying(100) NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    CONSTRAINT "PK_department" PRIMARY KEY (id),
    CONSTRAINT "FK_department_country_country_id" FOREIGN KEY (country_id) REFERENCES country (id) ON DELETE RESTRICT
);

CREATE TABLE municipality (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    department_id integer NOT NULL,
    name character varying(120) NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    CONSTRAINT "PK_municipality" PRIMARY KEY (id),
    CONSTRAINT "FK_municipality_department_department_id" FOREIGN KEY (department_id) REFERENCES department (id) ON DELETE RESTRICT
);

CREATE TABLE app_user (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    full_name character varying(120) NOT NULL,
    phone character varying(20) NOT NULL,
    address character varying(200) NOT NULL,
    municipality_id integer NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    CONSTRAINT "PK_app_user" PRIMARY KEY (id),
    CONSTRAINT "FK_app_user_municipality_municipality_id" FOREIGN KEY (municipality_id) REFERENCES municipality (id) ON DELETE RESTRICT
);

CREATE INDEX "IX_app_user_municipality_id" ON app_user (municipality_id);

CREATE UNIQUE INDEX "IX_country_iso2" ON country (iso2);

CREATE UNIQUE INDEX "IX_country_name" ON country (name);

CREATE INDEX "IX_department_country_id" ON department (country_id);

CREATE UNIQUE INDEX "IX_department_country_id_name" ON department (country_id, name);

CREATE INDEX "IX_municipality_department_id" ON municipality (department_id);

CREATE UNIQUE INDEX "IX_municipality_department_id_name" ON municipality (department_id, name);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260113185537_InitialSchema', '9.0.0');

COMMIT;

